name: Update AUR packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12,00 * * *'

jobs:
  update-aur:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          - dinox

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip makepkg
          pip3 install requests

      - name: Update AUR package
        env:
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
          GIT_EMAIL: ${{ vars.GIT_EMAIL }}
          GIT_NAME: ${{ vars.GIT_NAME }}          
        run: |
          python main.py -p ${{ matrix.package }}